<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://cxfservices.codereq.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="MathModuleImplService" targetNamespace="http://cxfservices.codereq.com/">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cxfservices.codereq.com/" elementFormDefault="unqualified" targetNamespace="http://cxfservices.codereq.com/" version="1.0">
            <xs:element name="isOdd" type="tns:isOdd"/>
            <xs:element name="isOddResponse" type="tns:isOddResponse"/>
            <xs:complexType name="isOdd">
                <xs:sequence>
                    <xs:element minOccurs="0" name="arg0" type="xs:int"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="isOddResponse">
                <xs:sequence>
                    <xs:element name="return" type="xs:boolean"/>
                </xs:sequence>
            </xs:complexType>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="isOddResponse">
        <wsdl:part element="tns:isOddResponse" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:message name="isOdd">
        <wsdl:part element="tns:isOdd" name="parameters"></wsdl:part>
    </wsdl:message>
    <wsdl:portType name="MathModule">
        <wsdl:operation name="isOdd">
            <wsdl:input message="tns:isOdd" name="isOdd"></wsdl:input>
            <wsdl:output message="tns:isOddResponse" name="isOddResponse"></wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MathModuleImplServiceSoapBinding" type="tns:MathModule">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="isOdd">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="isOdd">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="isOddResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MathModuleImplService">
        <wsdl:port binding="tns:MathModuleImplServiceSoapBinding" name="MathModuleImplPort">
            <soap:address location="http://localhost:8080/cxf-service-one/MathModule"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>